### ISSUE TITLE
Add demo page

### ISSUE THREAD

**Issue by pquerner** [codelandev/continent-country#1]
A demo page would be great.

Thanks.

**Comment by patrickemuller** [comment]
Hi @pquerner, thanks for feedback. I'll add a demo page ASAP.

**Comment by patrickemuller** [comment]
Hi @pquerner I'm created a github.io page to this Plugin...
My next step is to transform this into a gem! (if you work with Rails you can use this too)
http://codelandev.github.io/continent-country/

**Comment by pquerner** [comment]
Hi @mpatrick,
I get the following error in the console:
Refused to execute script from 'https://raw.githubusercontent.com/codelandev/continent-country/master/continent-countries-1.0-utf8.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Therefore the select boxes are completely empty.

Chrome Version 42.0.2311.39 beta-m (64-bit)

**Comment by patrickemuller** [comment]
@pquerner this is because Chrome blocks inline javascript.

From Chrome extension CSP Docs: "Inline JavaScript will not be executed. This restriction bans both inline `<script>` blocks and inline event handlers (e.g. `<button onclick="...">`)."

I'll move scripts for a specific file to avoid this.

**Comment by patrickemuller** [comment]
@pquerner Done.

**Comment by pquerner** [comment]
Awesome. Thank you. :)
